version: '3.8'
services: 
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
        
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - ./app:/app
        ports: 
            - 5000:5000
        build: ./app
        stdin_open: true
        tty: true
        depends_on: 
            - db
        links: 
            - db:db

    db:
        image: mysql:8.0.19
        restart: always
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: "space_station_Node"
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        ports: 
            - 3306:3306

volumes:
    db-data: